<?php
/**
 * Frontend logic for FlashAcademy Exit-Intent Modals.
 */

namespace FlashAcademy\FlashModals\Frontend;

use function FlashAcademy\FlashModals\asset_url;

defined( 'ABSPATH' ) || exit;

/**
 * Bootstrap frontend hooks.
 */
function setup(): void {
	add_action( 'wp_enqueue_scripts', __NAMESPACE__ . '\\enqueue_assets' );
	add_action( 'wp_footer', __NAMESPACE__ . '\\render_modal' );
}

/**
 * Choose the best matching active modal for current page.
 *
 * - Only considers flash_modal posts with:
 *   - faeim_active = 1
 *   - matching display rules (everywhere or include_pages)
 * - If multiple match, picks the one with highest faeim_priority.
 *
 * @return int|null Modal post ID or null if none match.
 */
function get_active_modal_id(): ?int {
	if ( ! function_exists( 'get_field' ) ) {
		return null; // ACF required.
	}

	$page_id = get_queried_object_id();

	$q = new \WP_Query(
		[
			'post_type'      => 'flash_modal',
			'post_status'    => 'publish',
			'posts_per_page' => -1,
			'meta_key'       => 'faeim_active',
			'meta_value'     => 1,
		]
	);

	if ( ! $q->have_posts() ) {
		return null;
	}

	$chosen_id   = null;
	$chosen_prio = -PHP_INT_MAX;

	while ( $q->have_posts() ) {
		$q->the_post();
		$id = get_the_ID();

		$active = (bool) get_field( 'faeim_active', $id );
		if ( ! $active ) {
			continue;
		}

		$show_everywhere = (bool) get_field( 'faeim_show_everywhere', $id );
		$include_pages   = get_field( 'faeim_include_pages', $id ); // array of IDs.

		$matches = false;

		if ( $show_everywhere ) {
			$matches = true;
		} elseif ( is_array( $include_pages ) && $page_id ) {
			$include_pages = array_map( 'intval', $include_pages );
			$matches       = in_array( (int) $page_id, $include_pages, true );
		}

		if ( ! $matches ) {
			continue;
		}

		$priority = (int) get_field( 'faeim_priority', $id );

		if ( $priority > $chosen_prio ) {
			$chosen_prio = $priority;
			$chosen_id   = $id;
		}
	}

	wp_reset_postdata();

	return $chosen_id ?: null;
}

/**
 * Enqueue frontend JS/CSS and localize config for the active modal.
 */
function enqueue_assets(): void {
	// DEBUG
	error_log('FAEIM: render_modal() running');
	$modal_id = get_active_modal_id();
	if ( ! $modal_id ) {
		return;
	}

	// Plugin root dir (frontend.php is in /inc).
	$plugin_dir = dirname( __DIR__ ) . '/';

	// Asset metadata generated by wp-scripts for faeim-modal-frontend.
	$asset_file = $plugin_dir . 'build/faeim-modal-frontend/index.asset.php';

	$deps    = [];
	$version = null;

	if ( file_exists( $asset_file ) ) {
		$asset   = require $asset_file;
		$deps    = $asset['dependencies'] ?? [];
		$version = $asset['version'] ?? null;
	}

	// SCSS compiled by wp-scripts:
	// src/faeim-modal-frontend/style.scss → build/style-faeim-modal-frontend.css.
	wp_enqueue_style(
		'faeim-modal',
		asset_url( 'build/style-faeim-modal-frontend.css' ),
		[],
		$version
	);

	// Main JS bundle (compiled & minified via wp-scripts).
	wp_enqueue_script(
		'faeim-modal',
		asset_url( 'build/faeim-modal-frontend/index.js' ),
		$deps,
		$version,
		true
	);

	// Localize config for JS (triggers, frequency, etc).
	if ( function_exists( 'get_field' ) ) {
		$config = [
			'modalId'       => $modal_id,
			'exitIntent'    => (bool) get_field( 'faeim_trigger_exit_intent', $modal_id ),
			'minTime'       => (int)  get_field( 'faeim_trigger_min_time', $modal_id ),
			'minScroll'     => (int)  get_field( 'faeim_trigger_min_scroll', $modal_id ),
			'frequencyDays' => (int)  get_field( 'faeim_frequency_days', $modal_id ),
			'pageId'        => get_queried_object_id(),
			// 'debug'      => true, // optional: wire an ACF toggle here if you want
		];

		wp_localize_script(
			'faeim-modal',
			'faeimConfig',
			$config
		);
	}
}

/**
 * Render the modal HTML at wp_footer.
 *
 * Markup is cloned from try-for-free.php, but the Gravity Form
 * is replaced with Gutenberg-rendered content ($content).
 */
function render_modal(): void {
	$modal_id = get_active_modal_id();
	if ( ! $modal_id ) {
		return;
	}

	$post = get_post( $modal_id );
	if ( ! $post ) {
		return;
	}

	// Gutenberg content (including Gravity Form block, etc.).
	$content      = apply_filters( 'the_content', $post->post_content );

	// Dynamic IDs so JS can target this instance.
	$modal_dom_id = 'faeim-modal-' . $modal_id;
	$label_id     = $modal_dom_id . '-label';
	?>
	<div
		class="modal fade form-modal faeim-modal"
		id="<?php echo esc_attr( $modal_dom_id ); ?>"
		tabindex="-1"
		aria-labelledby="<?php echo esc_attr( $label_id ); ?>"
		aria-hidden="true"
	>
		<div class="modal-dialog modal-dialog-centered form-modal__dialog">
			<div class="modal-content form-modal__content">
				<div class="modal-body form-modal__body">
					<div class="form-modal__grid">
						<button
							type="button"
							class="btn-close form-modal__grid-closeBtn"
							data-bs-dismiss="modal"
							aria-label="<?php esc_attr_e( 'Close', 'flashacademy-exit-intent-modal' ); ?>"
						></button>

						<div class="row form-modal__grid-row">
							<div class="col-xl-6 form-modal__grid-row-col">
								<div class="form-modal__grid-row-col-inner form-modal__grid-row-col-inner-left">
									<div class="form-modal__grid-row-col-inner-left-svgWrap">
										<?php
										// Same SVG call as template (theme function).
										if ( function_exists( 'insert_svg' ) ) {
											insert_svg(
												get_theme_file_uri( '/build/img/site-logo.svg' ),
												'site-logo'
											);
										}
										?>
									</div>
									<div class="form-modal__grid-row-col-inner-left-text tick-list">
										<p>
											Maximise your free trial with a demo from our expert that's customised
											around your bespoke need for boosting English language skills.
										</p>
										<ul>
											<li>Features <strong>48</strong> home languages to learn English.</li>
											<li>Integrates with your institutions MIS system.</li>
											<li>Supports learning of EAL, ESOL and MFL.</li>
										</ul>
									</div>
									<div class="form-modal__grid-row-col-inner-left-imgWrap">
										<img
											class="img-fluid form-modal__grid-row-col-inner-left-imgWrap-img"
											src="<?php echo esc_url( get_template_directory_uri() . '/build/img/pages/thank-you/teacher-and-student.png' ); ?>"
											alt=""
										/>
									</div>
								</div>
							</div>

							<div class="col-xl-6 form-modal__grid-row-col">
								<div class="form-modal__grid-row-col-inner form-modal__grid-row-col-inner-right">
									<h2
										id="<?php echo esc_attr( $label_id ); ?>"
										class="h3 form-modal__grid-row-col-inner-right-title"
									>
										Try For <span>Free</span>
									</h2>

									<?php
									// 🔁 This replaces the original Gravity Form in try-for-free.php.
									// Now we output Gutenberg-rendered content instead.
									echo $content; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped
									?>
								</div>
							</div>
						</div><!-- .form-modal__grid-row -->
					</div><!-- .form-modal__grid -->
				</div><!-- .form-modal__body -->
			</div><!-- .form-modal__content -->
		</div><!-- .form-modal__dialog -->
	</div><!-- .modal -->
	<?php
}
